### ISSUE TITLE
Parsing nils and empty string

### ISSUE THREAD

**Issue by langtianlang** [RubyMoney/monetize#47]
Currently nil and empty string returns a Money with value 0 in the default currency.

```
2.2.0 :044 > Monetize.parse(nil)
 => #<Money fractional:0 currency:USD>
2.2.0 :045 > Monetize.parse('')
 => #<Money fractional:0 currency:USD>
```

Is this the expected behavior?
From a client perspective, it seems like returning a nil return would make more sense since $0 is a legitimate value and shouldn't be used as the default for error cases.

**Comment by semmons99** [comment]
Yes, this is monetizes use case (be more liberal). The money gem itself would not accept these types of values.

**Comment by ct-clearhaus** [comment]
I am to blame; cf. https://github.com/RubyMoney/monetize/pull/42/files

However, I ensured that monetize follows money, namely `Money.new(nil) == nil.to_money`.

**Comment by bensheldon** [comment]
I appreciate that Monetize's contract is "Return a valid Money object or raise an ArgumentError". In normal usage, I do guard against nil/empty values, but I consider that the responsibility of my application because I may want to hand nil, empty or business-domain-specific-invalid in different ways depending on the application.

I think Monetize _could_ be much more configurable in regards to having a configurable unparseable outcome (e.g. pass in an optional lambda/proc that overrides the default of raise an ArgumentError), as well as configurable nil/null values (I could see a situation where I'd rather have nil or empty string raise an ArgumentError instead of being coerced to $0). But I also think this can easily be performed at the application layer (as I already do) rather than within the library.

Perhaps at the very least we could add a section to the Readme about **Expected Results** in regards to nil, empty-string, or unparseable inputs.

**Comment by langtianlang** [comment]
@bensheldon +1 to making the unparseable configurable.

Some what related to this, for my use case, there might be currencies I'm trying to parse that are not recognized by Monetize. It would be great if there's a way to throw an exception when it sees unknown currency types rather than just use the default currency.

@ct-clearhaus Another funky thing I noticed with nils in Money
```
2.2.0 :003 > Money.new(nil) == nil.to_money
 => true
2.2.0 :004 > Money.new(nil) == nil
 => true
2.2.0 :005 > Money.new(nil).nil?
 => false
```

**Comment by semmons99** [comment]
Sounds to me like you should use just the money gem and handle parsing in your application. 



- shane
