### ISSUE TITLE
Parsing number with 3 minors

### ISSUE THREAD

**Issue by mpoulsen** [RubyMoney/monetize#97]
When the currency.decimal_mark doesn't match the used decimal mark strange results occurs.

EUR's decimal_mark is ',' so everything works fine:
```
Money.default_currency = Money::Currency.new(:eur)

Monetize.extract_cents('1,0') # => 100
Monetize.extract_cents('1,00') # => 100
Monetize.extract_cents('1,000') # => 100
Monetize.extract_cents('1,0000') # => 100
```

USD's decimal_mark is '.' so parsing '1,000' is a problem:

```
Money.default_currency = Money::Currency.new(:usd)

Monetize.extract_cents('1,0') # => 100
Monetize.extract_cents('1,00') # => 100
Monetize.extract_cents('1,000') # => 100000
Monetize.extract_cents('1,0000') # => 100
```

It happens here: https://github.com/RubyMoney/monetize/blob/master/lib/monetize.rb#L203

I also seems strange to at all look at the currencies decimal_mark. This should depend on the locale.

**Comment by antstorm** [comment]
@mpoulsen yeah, looks like it's looking for 3 digits after `,` (thousands separator), that's why only `1,000` gets parsed correctly. I agree this is confusing and should be based on the locale instead. Happy to accept a PR with this change.

**Comment by yez** [comment]
@mpoulsen , @antstorm I'm interested in fixing this. What is the desired outcome of `Monetize.extract_cents('1,000')`? Should it return `100` since it does not specify cents at all or should it convert `$1,000` to `100,000 cents`?

**Comment by antstorm** [comment]
@yez great! I think during the parsing process we can just strip out thousands separators from the input. I think the problem is in trying to figure what is a decimal mark and what is a thousands separator based on the input.

I'm also not sure whether the current "let's parse any input" approach is the right way to go. For me it makes sense to make developers choose between strict and flexible parsing modes, allowing them to asses the risk of their application.

**Comment by yez** [comment]
I agree that having it be flexible would be best. However, it seems that if we try to just strip out the thousands place delimiter we will have the same problem as demonstrated above (since some currencies use `,` and others use `.` for thousands separator. How would we know which to strip? 

i.e. `1,000 EUR` is really `1 EUR` and `1.000 USD` is really `1 USD`. 

My original question was: If we try and `extract_cents` from `1,000 USD`, should it return the total value of the currency in cents (`1,000 * 100 = 100,000`)?

**Comment by antstorm** [comment]
@yez I think so yes.

We can strip the thousands separator once we're sure about the currency. This is why the parser will first try to determine the target currency then use it's thousands separator or try to figure out (basically treating the last symbol as a decimal mark).

There's also a rule that the thousands separator should have a multiple of 3 digits after it before another sign. If there isn't it's treated as a decimal mark, hence `1,00 USD == 1 USD` and `1,000 USD == 1000 USD`

**Comment by Drowze** [comment]
_few year later_

An update to this issue: the current behaviour is
```ruby
require 'monetize'
Money.default_currency = 'USD'
Monetize.parse('1,000') # => <Money fractional:100000 currency:USD>

Money.default_currency = 'EUR'
Monetize.parse('1,000') # => <Money fractional:100 currency:EUR>
```

**Comment by antstorm** [comment]
@Drowze yeah, unfortunately the current parser gets too excited when it sees currency definition in the string and wants to apply its defaults straight away. From the looks of it there unfortunately isn't a simple workaround, apart from maybe re-registering those currencies (`Money.register`).

I am slowly working on a new parser (https://github.com/antstorm/monetize/blob/new-parser/lib/monetize/new_parser.rb) and this is really good input. Currently it assumes a single delimiter to represent a decimal mark (https://github.com/antstorm/monetize/blob/new-parser/lib/monetize/new_parser.rb#L78), but we should probably allow overriding this behaviour via options.
